name: pynta_env
channels:
  - defaults
  - mjohnson541
  - conda-forge
dependencies:
  - python =3.8
  - matplotlib
  - spglib
  - ase >=3.22.1
  - scipy >=1.1.0
  - numpy
  - pyyaml
  - sella >=2.2.1
  - sphinx
  - anaconda::glpk
  - fireworks
  - jax <=0.2.28
  - xtb >=6.4.1
  - xtb-python >=20.2
  - rmgmolecule
  - acat
  - libffi <=3.3
  - nose
  - coverage
  - liblapack !=3.9.0
  - pysidt
  - pyyaml <6
